project_id = "jnbosvnshcefcsbaouuj"

[functions.analyze-movie]
verify_jwt = false

[functions.trending-movies]
verify_jwt = false

[functions.similar-movies]
verify_jwt = false

[functions.mood-recommendations]
verify_jwt = false
